export const products = [
  {
    id: 1,
    name: {
      mk: 'Сара Категорија А',
      sr: 'Сара Категорија А',
      sq: 'Sara Kategoria A',
      en: 'Sara Category A',
    },
    description: {
      mk: 'Краток опис на производот со важни карактеристики.',
      sr: 'Kratak opis proizvoda sa važnim karakteristikama.',
      sq: 'Përshkrim i shkurtër i produktit me karakteristika të rëndësishme.',
      en: 'Short product description with key features.',
    },
    category: 'tools',
    price: 79.9,
    sku: 'SARA-A-001',
  },
  {
    id: 2,
    name: {
      mk: 'Сара Категорија Б',
      sr: 'Сара Категорија Б',
      sq: 'Sara Kategoria B',
      en: 'Sara Category B',
    },
    description: {
      mk: 'Квалитетен производ за професионална употреба.',
      sr: 'Kvalitetan proizvod za profesionalnu upotrebu.',
      sq: 'Produkt cilësor për përdorim profesional.',
      en: 'Quality product for professional use.',
    },
    category: 'measurements',
    price: 59.5,
    sku: 'SARA-B-002',
  },
  {
    id: 3,
    name: {
      mk: 'Сара Категорија Ц',
      sr: 'Сара Категорија Ц',
      sq: 'Sara Kategoria C',
      en: 'Sara Category C',
    },
    description: {
      mk: 'Добар за секојдневна употреба и мала работилница.',
      sr: 'Dobar za svakodnevnu upotrebu i malu radionicu.',
      sq: 'I mirë për përdorim të përditshëm dhe punëtori të vogël.',
      en: 'Good for everyday use and small workshop.',
    },
    category: 'accessories',
    price: 24.75,
    sku: 'SARA-C-003',
  },
  {
    id: 4,
    name: {
      mk: 'Сара Категорија Д',
      sr: 'Сара Категорија Д',
      sq: 'Sara Kategoria D',
      en: 'Sara Category D',
    },
    description: {
      mk: 'Технички производ со висок квалитет на материјали.',
      sr: 'Tehnički proizvod sa visokim kvalitetom materijala.',
      sq: 'Produkt teknik me cilësi të lartë të materialeve.',
      en: 'Technical product with high-quality materials.',
    },
    category: 'tools',
    price: 129.9,
    sku: 'SARA-D-004',
  },
  {
    id: 5,
    name: {
      mk: 'Сара Категорија Е',
      sr: 'Сара Категорија Е',
      sq: 'Sara Kategoria E',
      en: 'Sara Category E',
    },
    description: {
      mk: 'Компактен сет за брзо и прецизно мерење.',
      sr: 'Kompaktan set za brzo i precizno merenje.',
      sq: 'Set kompakt për matje të shpejtë dhe të saktë.',
      en: 'Compact set for fast and precise measurement.',
    },
    category: 'measurements',
    price: 45.0,
    sku: 'SARA-E-005',
  },
];

export const translations = {
  mk: {
    title: 'Онлајн каталог',
    subtitle: 'Прегледајте и избирајте производи. Додадете во кошничка за да добиете цена.',
    languageLabel: 'Јазик',
    searchPlaceholder: 'Пребарај по име, SKU или опис…',
    categoryAll: 'Сите категории',
    categories: {
      tools: 'Алатки',
      measurements: 'Мерења',
      accessories: 'Аксесоари',
    },
    addToCart: 'Додади во кошничка',
    remove: 'Избриши',
    cartTitle: 'Кошничка',
    emptyCart: 'Кошничката е празна',
    noProducts: 'Нема продукти за прикажување',
    total: 'Вкупно',
    checkoutNote: 'Нема онлајн продажба, ова е само за пресметка на цена.',
    quantity: 'Количина',
    productCode: 'Код',
    cartItem: 'продукт(и) во кошничка',
  },
  sr: {
    title: 'Онлајн каталог',
    subtitle: 'Pregledajte i birajte proizvode. Dodajte u korpu da dobijete cenu.',
    languageLabel: 'Jezik',
    searchPlaceholder: 'Pretražite po imenu, SKU ili opisu…',
    categoryAll: 'Sve kategorije',
    categories: {
      tools: 'Alatke',
      measurements: 'Merenja',
      accessories: 'Aksesoari',
    },
    addToCart: 'Dodaj u korpu',
    remove: 'Obriši',
    cartTitle: 'Korpa',
    emptyCart: 'Korpa je prazna',
    noProducts: 'Nema proizvoda za prikaz',
    total: 'Ukupno',
    checkoutNote: 'Nema online prodaje, ovo je samo za proračun cene.',
    quantity: 'Količina',
    productCode: 'Kod',
    cartItem: 'proizvod(a) u korpi',
  },
  sq: {
    title: 'Katalog Online',
    subtitle: 'Shfletoni dhe zgjidhni produkte. Shtoni në karrocë për të marrë çmimin.',
    languageLabel: 'Gjuha',
    searchPlaceholder: 'Kërko sipas emrit, SKU ose përshkrimit…',
    categoryAll: 'Të gjitha kategoritë',
    categories: {
      tools: 'Vegla',
      measurements: 'Matje',
      accessories: 'Aksesorë',
    },
    addToCart: 'Shto në karrocë',
    remove: 'Fshi',
    cartTitle: 'Karroca',
    emptyCart: 'Karroca është bosh',
    noProducts: 'Nuk ka produkte për t’u shfaqur',
    total: 'Totali',
    checkoutNote: 'Nuk ka shitje online, kjo është vetëm për llogaritjen e çmimit.',
    quantity: 'Sasia',
    productCode: 'Kodi',
    cartItem: 'produkt(ë) në karrocë',
  },
  en: {
    title: 'Online Catalogue',
    subtitle: 'Browse and select products. Add to cart to get a price estimate.',
    languageLabel: 'Language',
    searchPlaceholder: 'Search by name, SKU, or description…',
    categoryAll: 'All categories',
    categories: {
      tools: 'Tools',
      measurements: 'Measurements',
      accessories: 'Accessories',
    },
    addToCart: 'Add to cart',
    remove: 'Remove',
    cartTitle: 'Cart',
    emptyCart: 'The cart is empty',
    noProducts: 'No products to display',
    total: 'Total',
    checkoutNote: 'No online sales, this is only for price calculation.',
    quantity: 'Quantity',
    productCode: 'Code',
    cartItem: 'item(s) in cart',
  },
};
