export const products = [
  {
    id: 1,
    name: {
      mk: 'Сара Категорија А',
      sr: 'Сара Категорија А',
      sq: 'Sara Kategoria A',
      en: 'Sara Category A',
    },
    description: {
      mk: 'Краток опис на производот со важни карактеристики.',
      sr: 'Kratak opis proizvoda sa važnim karakteristikama.',
      sq: 'Përshkrim i shkurtër i produktit me karakteristika të rëndësishme.',
      en: 'Short product description with key features.',
    },
    category: 'tools',
    price: 79.9,
    sku: 'SARA-A-001',
  },
  {
    id: 2,
    name: {
      mk: 'Сара Категорија Б',
      sr: 'Сара Категорија Б',
      sq: 'Sara Kategoria B',
      en: 'Sara Category B',
    },
    description: {
      mk: 'Квалитетен производ за професионална употреба.',
      sr: 'Kvalitetan proizvod za profesionalnu upotrebu.',
      sq: 'Produkt cilësor për përdorim profesional.',
      en: 'Quality product for professional use.',
    },
    category: 'measurements',
    price: 59.5,
    sku: 'SARA-B-002',
  },
  {
    id: 3,
    name: {
      mk: 'Сара Категорија Ц',
      sr: 'Сара Категорија Ц',
      sq: 'Sara Kategoria C',
      en: 'Sara Category C',
    },
    description: {
      mk: 'Добар за секојдневна употреба и мала работилница.',
      sr: 'Dobar za svakodnevnu upotrebu i malu radionicu.',
      sq: 'I mirë për përdorim të përditshëm dhe punëtori të vogël.',
      en: 'Good for everyday use and small workshop.',
    },
    category: 'accessories',
    price: 24.75,
    sku: 'SARA-C-003',
  },
  {
    id: 4,
    name: {
      mk: 'Сара Категорија Д',
      sr: 'Сара Категорија Д',
      sq: 'Sara Kategoria D',
      en: 'Sara Category D',
    },
    description: {
      mk: 'Технички производ со висок квалитет на материјали.',
      sr: 'Tehnički proizvod sa visokim kvalitetom materijala.',
      sq: 'Produkt teknik me cilësi të lartë të materialeve.',
      en: 'Technical product with high-quality materials.',
    },
    category: 'tools',
    price: 129.9,
    sku: 'SARA-D-004',
  },
  {
    id: 5,
    name: {
      mk: 'Сара Категорија Е',
      sr: 'Сара Категорија Е',
      sq: 'Sara Kategoria E',
      en: 'Sara Category E',
    },
    description: {
      mk: 'Компактен сет за брзо и прецизно мерење.',
      sr: 'Kompaktan set za brzo i precizno merenje.',
      sq: 'Set kompakt për matje të shpejtë dhe të saktë.',
      en: 'Compact set for fast and precise measurement.',
    },
    category: 'measurements',
    price: 45.0,
    sku: 'SARA-E-005',
  },
];

export const translations = {
  mk: {
    title: 'Онлајн каталог',
    subtitle: 'Прегледајте и избирајте производи. Додадете во кошничка за да нарачате.',
    languageLabel: 'Јазик',
    searchPlaceholder: 'Пребарај по ime, SKU или опис…',
    categoryAll: 'Сите категории',
    categories: {
      tools: 'Алатки',
      measurements: 'Мерења',
      accessories: 'Аксесоари',
    },
    addToCart: 'Додади во кошничка',
    remove: 'Избриши',
    cartTitle: 'Кошничка',
    emptyCart: 'Кошничката е празна',
    noProducts: 'Нема продукти за прикажување',
    total: 'Вкупно',
    checkoutNote: 'Најавете се за да направите нарачка.',
    placeOrder: 'Нарачај',
    continueOrder: 'Продолжи со нарачка',
    orderSuccess: 'Нарачката е успешно испратена!',
    quantity: 'Количина',
    productCode: 'Код',
    cartItem: 'продукт(и) во кошничка',
    login: 'Најави се',
    register: 'Регистрирај се',
    logout: 'Одјави се',
    loginTitle: 'Најава',
    registerTitle: 'Нова сметка',
    email: 'Е-пошта',
    name: 'Име и презиме',
    password: 'Лозинка',
    loginBtn: 'Најави се',
    registerBtn: 'Создај сметка',
    noAccount: 'Немате сметка?',
    hasAccount: 'Веќе имате сметка?',
    myOrders: 'Мои нарачки',
    ordersTitle: 'Мои нарачки',
    orderDate: 'Датум',
    orderStatus: 'Статус',
    orderTotal: 'Вкупно',
    noOrders: 'Немате нарачки сè уште.',
    orderNote: 'Забелешка (незадолжително)',
  },
  sr: {
    title: 'Онлајн каталог',
    subtitle: 'Pregledajte i birajte proizvode. Dodajte u korpu da naručite.',
    languageLabel: 'Jezik',
    searchPlaceholder: 'Pretražite po imenu, SKU ili opisu…',
    categoryAll: 'Sve kategorije',
    categories: {
      tools: 'Alatke',
      measurements: 'Merenja',
      accessories: 'Aksesoari',
    },
    addToCart: 'Dodaj u korpu',
    remove: 'Obriši',
    cartTitle: 'Korpa',
    emptyCart: 'Korpa je prazna',
    noProducts: 'Nema proizvoda za prikaz',
    total: 'Ukupno',
    checkoutNote: 'Prijavite se da biste napravili narudžbu.',
    placeOrder: 'Naruči',
    continueOrder: 'Nastavi sa narudžbom',
    orderSuccess: 'Narudžba je uspešno poslata!',
    quantity: 'Količina',
    productCode: 'Kod',
    cartItem: 'proizvod(a) u korpi',
    login: 'Prijavi se',
    register: 'Registruj se',
    logout: 'Odjavi se',
    loginTitle: 'Prijava',
    registerTitle: 'Novi nalog',
    email: 'E-pošta',
    name: 'Ime i prezime',
    password: 'Lozinka',
    loginBtn: 'Prijavi se',
    registerBtn: 'Napravi nalog',
    noAccount: 'Nemate nalog?',
    hasAccount: 'Već imate nalog?',
    myOrders: 'Moje narudžbe',
    ordersTitle: 'Moje narudžbe',
    orderDate: 'Datum',
    orderStatus: 'Status',
    orderTotal: 'Ukupno',
    noOrders: 'Nemate narudžbi još.',
    orderNote: 'Napomena (opciono)',
  },
  sq: {
    title: 'Katalog Online',
    subtitle: 'Shfletoni dhe zgjidhni produkte. Shtoni në karrocë për të porositur.',
    languageLabel: 'Gjuha',
    searchPlaceholder: 'Kërko sipas emrit, SKU ose përshkrimit…',
    categoryAll: 'Të gjitha kategoritë',
    categories: {
      tools: 'Vegla',
      measurements: 'Matje',
      accessories: 'Aksesorë',
    },
    addToCart: 'Shto në karrocë',
    remove: 'Fshi',
    cartTitle: 'Karroca',
    emptyCart: 'Karroca është bosh',
    noProducts: "Nuk ka produkte për t'u shfaqur",
    total: 'Totali',
    checkoutNote: 'Hyni për të bërë një porosi.',
    placeOrder: 'Porosit',
    continueOrder: 'Vazhdo me porosinë',
    orderSuccess: 'Porosia u dërgua me sukses!',
    quantity: 'Sasia',
    productCode: 'Kodi',
    cartItem: 'produkt(ë) në karrocë',
    login: 'Hyr',
    register: 'Regjistrohu',
    logout: 'Dil',
    loginTitle: 'Hyrja',
    registerTitle: 'Llogari e re',
    email: 'E-mail',
    name: 'Emri dhe mbiemri',
    password: 'Fjalëkalimi',
    loginBtn: 'Hyr',
    registerBtn: 'Krijo llogari',
    noAccount: 'Nuk keni llogari?',
    hasAccount: 'Keni tashmë llogari?',
    myOrders: 'Porositë e mia',
    ordersTitle: 'Porositë e mia',
    orderDate: 'Data',
    orderStatus: 'Statusi',
    orderTotal: 'Totali',
    noOrders: 'Nuk keni porosi ende.',
    orderNote: 'Shënim (opsional)',
  },
  en: {
    title: 'Online Catalogue',
    subtitle: 'Browse and select products. Add to cart to place an order.',
    languageLabel: 'Language',
    searchPlaceholder: 'Search by name, SKU, or description…',
    categoryAll: 'All categories',
    categories: {
      tools: 'Tools',
      measurements: 'Measurements',
      accessories: 'Accessories',
    },
    addToCart: 'Add to cart',
    remove: 'Remove',
    cartTitle: 'Cart',
    emptyCart: 'The cart is empty',
    noProducts: 'No products to display',
    total: 'Total',
    checkoutNote: 'Log in to place an order.',
    placeOrder: 'Place order',
    continueOrder: 'Continue with order',
    orderSuccess: 'Order placed successfully!',
    quantity: 'Quantity',
    productCode: 'Code',
    cartItem: 'item(s) in cart',
    login: 'Log in',
    register: 'Register',
    logout: 'Log out',
    loginTitle: 'Log in',
    registerTitle: 'New account',
    email: 'Email',
    name: 'Full name',
    password: 'Password',
    loginBtn: 'Log in',
    registerBtn: 'Create account',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    myOrders: 'My orders',
    ordersTitle: 'My orders',
    orderDate: 'Date',
    orderStatus: 'Status',
    orderTotal: 'Total',
    noOrders: 'You have no orders yet.',
    orderNote: 'Note (optional)',
  },
};
